#!/bin/bash
#get access token
#trying to write a bash script to automate this two post request
#if this fails i'll just use good old python :/
var = "$(curl --request POST0 --url https://dev-42331gx2.us.auth0.com/oauth/token  --header 'content-type: application/json' --data '{"client_id":"Goi7MZiF0YCI4YAykw5gbd5Xky8s4JUj","client_secret":"v6sEKlu8WE6OVGpSXamVLEM8W9_IKSwg6eeaQJmY0qdCIrLfhfQP1j-GRDSOEL6K","audience":"sams-dwh-web-api","grant_type":"client_credentials"}')"

